@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class, kotlinx.cinterop.BetaInteropApi::class)

package com.ditchoom.socket.quic

import com.ditchoom.socket.quic.nwquic26.NWQuic26Bridge
import com.ditchoom.socket.quic.nwquic26.NWQuic26Conn
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.time.Duration.Companion.seconds

/**
 * PLAN step 2 (real bridge — datagram slice): drives the OS-26 `NetworkConnection<QUIC>` Swift API end
 * to end through the `@objc` bridge — a server (`listen`) + client (`connect`) loopback in which the
 * client sends an unreliable QUIC DATAGRAM and the server echoes it back, all over a single connection.
 * This is the capability the legacy `nw_connection_group` backend cannot deliver alongside streams
 * (issue #173); proving it through the K/N bridge is the foundation the stream + server-wiring steps
 * build on. Mirrors `socket-quic-nw/os26-bridge-reference.swift`.
 *
 * The server presents the W3C `pinned` EC P-256 identity; the client pins its SHA-256 leaf hash
 * (`pinned.sha256`, generated by `generateTestP12`) so the self-signed cert validates via the shim's
 * Swift-side hash comparison (HashOnly — no chain check). macosArm64-only, like the build-plumbing
 * spike, because the `NWQuic26` cinterop bindings are per-target (not commonized into `appleTest`).
 */
class NWQuic26BridgeDatagramTest {
    @Test
    fun clientServerDatagramRoundTrip() =
        runBlocking {
            withTimeout(25.seconds) {
                val alpn = listOf("nwq26-dgram-test")
                val p12 = testCertPath("pinned.p12")
                val pinHash = pinFor("pinned")

                val bridge = NWQuic26Bridge()

                // --- server: echo each inbound datagram back to the sender ---
                val serverPort = CompletableDeferred<Int>()
                val listener =
                    bridge.listenWithHost(
                        host = "127.0.0.1",
                        port = 0u,
                        alpn = alpn,
                        p12Path = p12,
                        p12Password = "testpass",
                        idleTimeoutMs = 30_000,
                        maxDatagramFrameSize = 1200,
                        keepAliveMs = 0,
                        onConnection = { conn ->
                            // K/N imports _Nonnull ObjC block params as nullable; they're never null here.
                            val c = conn!!
                            c.onDatagram { data -> c.sendDatagram(data!!) { _, _ -> } }
                        },
                        onListenerState = { errCode, boundPort, desc ->
                            if (errCode == 0) {
                                serverPort.complete(boundPort.toInt())
                            } else {
                                serverPort.completeExceptionally(IllegalStateException("listener failed: $errCode ${desc ?: ""}"))
                            }
                        },
                    )
                val port = serverPort.await()

                // --- client: connect (pinning the server leaf hash), then datagram round-trip ---
                // clientRef is assigned from connectWithHost's return (synchronous) before onReady — an
                // async post-handshake callback — can fire, so the closure reads the live pin reason.
                val clientReady = CompletableDeferred<Unit>()
                var clientRef: NWQuic26Conn? = null
                val client =
                    bridge.connectWithHost(
                        host = "127.0.0.1",
                        port = port.toUShort(),
                        alpn = alpn,
                        idleTimeoutMs = 30_000,
                        maxDatagramFrameSize = 1200,
                        keepAliveMs = 0,
                        serverCertificateHashes = listOf(pinHash),
                        requireChain = false,
                        verifyPeer = true,
                        onReady = { errCode, desc ->
                            if (errCode == 0) {
                                clientReady.complete(Unit)
                            } else {
                                clientReady.completeExceptionally(
                                    IllegalStateException(
                                        "connect failed: $errCode ${desc ?: ""} pinReason=${clientRef?.pinFailureReason()}",
                                    ),
                                )
                            }
                        },
                    )
                clientRef = client
                clientReady.await()

                val echoed = CompletableDeferred<String>()
                client.onDatagram { data -> echoed.complete(data!!.toByteArray().decodeToString()) }

                val sent = CompletableDeferred<Unit>()
                val payload = "cli-dg".encodeToByteArray().toNSData()
                client.sendDatagram(payload) { errCode, desc ->
                    if (errCode == 0) {
                        sent.complete(Unit)
                    } else {
                        sent.completeExceptionally(IllegalStateException("send failed: $errCode ${desc ?: ""}"))
                    }
                }
                sent.await()

                assertEquals("cli-dg", echoed.await())

                client.closeWithAppErrorCode(0u)
                listener.cancel()
            }
        }
}
