@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class, kotlinx.cinterop.BetaInteropApi::class)

package com.ditchoom.socket.quic

import com.ditchoom.socket.quic.nwquic26.NWQuic26Bridge
import com.ditchoom.socket.quic.nwquic26.NWQuic26Conn
import kotlinx.cinterop.ByteVar
import kotlinx.cinterop.addressOf
import kotlinx.cinterop.allocArray
import kotlinx.cinterop.convert
import kotlinx.cinterop.get
import kotlinx.cinterop.memScoped
import kotlinx.cinterop.set
import kotlinx.cinterop.toKString
import kotlinx.cinterop.usePinned
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import platform.Foundation.NSData
import platform.Foundation.create
import platform.posix.F_OK
import platform.posix.access
import platform.posix.fclose
import platform.posix.fopen
import platform.posix.fread
import platform.posix.memcpy
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.time.Duration.Companion.seconds

/**
 * PLAN step 2 (real bridge — datagram slice): drives the OS-26 `NetworkConnection<QUIC>` Swift API end
 * to end through the `@objc` bridge — a server (`listen`) + client (`connect`) loopback in which the
 * client sends an unreliable QUIC DATAGRAM and the server echoes it back, all over a single connection.
 * This is the capability the legacy `nw_connection_group` backend cannot deliver alongside streams
 * (issue #173); proving it through the K/N bridge is the foundation the stream + server-wiring steps
 * build on. Mirrors `socket-quic-nw/os26-bridge-reference.swift`.
 *
 * The server presents the W3C `pinned` EC P-256 identity; the client pins its SHA-256 leaf hash
 * (`pinned.sha256`, generated by `generateTestP12`) so the self-signed cert validates via the shim's
 * Swift-side hash comparison (HashOnly — no chain check). macosArm64-only, like the build-plumbing
 * spike, because the `NWQuic26` cinterop bindings are per-target (not commonized into `appleTest`).
 */
class NWQuic26BridgeDatagramTest {
    @Test
    fun clientServerDatagramRoundTrip() =
        runBlocking {
            withTimeout(25.seconds) {
                val alpn = listOf("nwq26-dgram-test")
                val p12 = testCertPath("pinned.p12")
                val pinHash = readFileText(testCertPath("pinned.sha256")).trim().hexToByteArray().toNSData()

                val bridge = NWQuic26Bridge()

                // --- server: echo each inbound datagram back to the sender ---
                val serverPort = CompletableDeferred<Int>()
                val listener =
                    bridge.listenWithHost(
                        host = "127.0.0.1",
                        port = 0u,
                        alpn = alpn,
                        p12Path = p12,
                        p12Password = "testpass",
                        idleTimeoutMs = 30_000,
                        maxDatagramFrameSize = 1200,
                        keepAliveMs = 0,
                        onConnection = { conn ->
                            // K/N imports _Nonnull ObjC block params as nullable; they're never null here.
                            val c = conn!!
                            c.onDatagram { data -> c.sendDatagram(data!!) { _, _ -> } }
                        },
                        onListenerState = { errCode, boundPort, desc ->
                            if (errCode == 0) {
                                serverPort.complete(boundPort.toInt())
                            } else {
                                serverPort.completeExceptionally(IllegalStateException("listener failed: $errCode ${desc ?: ""}"))
                            }
                        },
                    )
                val port = serverPort.await()

                // --- client: connect (pinning the server leaf hash), then datagram round-trip ---
                // clientRef is assigned from connectWithHost's return (synchronous) before onReady — an
                // async post-handshake callback — can fire, so the closure reads the live pin reason.
                val clientReady = CompletableDeferred<Unit>()
                var clientRef: NWQuic26Conn? = null
                val client =
                    bridge.connectWithHost(
                        host = "127.0.0.1",
                        port = port.toUShort(),
                        alpn = alpn,
                        idleTimeoutMs = 30_000,
                        maxDatagramFrameSize = 1200,
                        keepAliveMs = 0,
                        serverCertificateHashes = listOf(pinHash),
                        requireChain = false,
                        onReady = { errCode, desc ->
                            if (errCode == 0) {
                                clientReady.complete(Unit)
                            } else {
                                clientReady.completeExceptionally(
                                    IllegalStateException(
                                        "connect failed: $errCode ${desc ?: ""} pinReason=${clientRef?.pinFailureReason()}",
                                    ),
                                )
                            }
                        },
                    )
                clientRef = client
                clientReady.await()

                val echoed = CompletableDeferred<String>()
                client.onDatagram { data -> echoed.complete(data!!.toByteArray().decodeToString()) }

                val sent = CompletableDeferred<Unit>()
                val payload = "cli-dg".encodeToByteArray().toNSData()
                client.sendDatagram(payload) { errCode, desc ->
                    if (errCode == 0) {
                        sent.complete(Unit)
                    } else {
                        sent.completeExceptionally(IllegalStateException("send failed: $errCode ${desc ?: ""}"))
                    }
                }
                sent.await()

                assertEquals("cli-dg", echoed.await())

                client.closeWithAppErrorCode(0u)
                listener.cancel()
            }
        }
}

// --- self-contained helpers (macosArm64Test can't see appleTest's shared helpers) ---

private fun testCertPath(name: String): String =
    listOf("testcerts/$name", "socket-quic-nw/testcerts/$name")
        .firstOrNull { access(it, F_OK) == 0 }
        ?: error("Test cert not found: $name (did generateTestP12 run?)")

private fun readFileText(path: String): String =
    memScoped {
        val fp = fopen(path, "r") ?: error("Cannot open $path")
        try {
            val sb = StringBuilder()
            val bufSize = 4096
            val buf = allocArray<ByteVar>(bufSize)
            while (true) {
                val n = fread(buf, 1.convert(), (bufSize - 1).convert(), fp).toInt()
                if (n <= 0) break
                buf[n] = 0
                sb.append(buf.toKString())
            }
            sb.toString()
        } finally {
            fclose(fp)
        }
    }

private fun String.hexToByteArray(): ByteArray =
    ByteArray(length / 2) { ((this[it * 2].digitToInt(16) shl 4) or this[it * 2 + 1].digitToInt(16)).toByte() }

private fun ByteArray.toNSData(): NSData =
    if (isEmpty()) {
        NSData()
    } else {
        usePinned { pinned -> NSData.create(bytes = pinned.addressOf(0), length = size.convert()) }
    }

private fun NSData.toByteArray(): ByteArray {
    val len = length.toInt()
    if (len == 0) return ByteArray(0)
    val out = ByteArray(len)
    out.usePinned { pinned -> memcpy(pinned.addressOf(0), bytes, length) }
    return out
}
