plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

/*
 * :ios-probe — the iOS half of the real-handoff rig.
 *
 * NOT part of the published library and NOT wired into CI: it exists so a person can walk out of a
 * building with an iPhone and record what a QUIC connection does when the path underneath it dies.
 * It is a module in the repo rather than a scratch directory on purpose — the previous iOS probe
 * lived only as untracked files under /tmp and was destroyed by the system's temp cleaner, taking
 * the whole rig with it.
 *
 * Produces a dynamic framework the Xcode app in `iosApp/` links. Dynamic, not static, because the
 * quiche static archive reaches the app through this framework's link step.
 */
repositories {
    google()
    mavenCentral()
}

// The commit this probe was built from, stamped as a constant for its START line. Runs on every build
// because the answer moves with every commit and edit, but rewrites the file only when the stamp
// changed. Empty when git had no answer, which the probe reports as `build=unknown(NotStamped)`.
val buildStampDir = layout.buildDirectory.dir("generated/buildStamp/kotlin")
val generateBuildStamp =
    tasks.register("generateBuildStamp") {
        val repo = rootProject.projectDir
        val out = buildStampDir
        outputs.dir(out)
        outputs.upToDateWhen { false }
        doLast {
            fun git(vararg args: String): String? =
                runCatching {
                    val process = ProcessBuilder(listOf("git", *args)).directory(repo).start()
                    val text = process.inputStream.bufferedReader().readText().trim()
                    text.takeIf { process.waitFor() == 0 }
                }.getOrNull()
            val sha = git("rev-parse", "HEAD").orEmpty()
            val dirty = sha.isNotEmpty() && git("status", "--porcelain", "--untracked-files=no").orEmpty().isNotEmpty()
            val stamp = if (dirty) "$sha+dirty" else sha
            val file = out.get().asFile.resolve("com/ditchoom/socket/quic/probe/ProbeBuildStamp.kt")
            val text =
                "// Generated by :ios-probe:generateBuildStamp — DO NOT EDIT.\n" +
                    "package com.ditchoom.socket.quic.probe\n\n" +
                    "/** The commit this probe was built from: `<sha>`, `<sha>+dirty`, or empty when git had no answer. */\n" +
                    "internal const val PROBE_BUILD_STAMP: String = \"$stamp\"\n"
            if (!file.exists() || file.readText() != text) {
                file.parentFile.mkdirs()
                file.writeText(text)
            }
        }
    }

kotlin {
    iosArm64 {
        binaries.framework {
            baseName = "probe"
        }
    }

    sourceSets {
        iosArm64Main {
            kotlin.srcDir(generateBuildStamp.map { buildStampDir.get() })
            dependencies {
                implementation(project(":socket-quic-default"))
                // The #447 pool-recovery verdict is one decision shared with the Android probe;
                // two copies of it is how the two drifted into passing a connection that never
                // recovered. :socket-testkit keeps kotlin.test out of its main source set, so it
                // links into a shipping probe app without dragging a test framework along.
                implementation(project(":socket-testkit"))
                implementation(libs.kotlinx.coroutines.core)
            }
        }
    }
}
