package com.ditchoom.socket.http3

import com.ditchoom.buffer.BufferFactory
import com.ditchoom.buffer.Default
import com.ditchoom.buffer.codec.DecodeContext
import com.ditchoom.buffer.codec.EncodeContext
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * End-to-end validation of the buffer-codec KSP-for-main pipeline: [Http3SettingsPairCodec]
 * is GENERATED by the processor into commonMain and must compile + round-trip on every
 * target. It also exercises the custom `@UseCodec(QuicVarIntCodec)` scalar codec for both
 * varint fields. If this test compiles, KSP-for-main + `@UseCodec` are working.
 */
class Http3SettingsPairTest {
    @Test
    fun roundTripsThroughGeneratedCodec() {
        // SETTINGS_QPACK_MAX_TABLE_CAPACITY (0x01) = 4096 — both fit varint encodings.
        val pair = Http3SettingsPair(identifier = 0x01, value = 4096)
        val buf = BufferFactory.Default.allocate(16)
        Http3SettingsPairCodec.encode(buf, pair, EncodeContext.Empty)
        buf.resetForRead()
        assertEquals(pair, Http3SettingsPairCodec.decode(buf, DecodeContext.Empty))
    }

    @Test
    fun roundTripsLargeVarintValues() {
        val pair = Http3SettingsPair(identifier = 0x06, value = 151288809941952652L)
        val buf = BufferFactory.Default.allocate(16)
        Http3SettingsPairCodec.encode(buf, pair, EncodeContext.Empty)
        buf.resetForRead()
        assertEquals(pair, Http3SettingsPairCodec.decode(buf, DecodeContext.Empty))
    }
}
