// GENERATED by TraceToFixture from recorded trace "walk-2026-09-10-conn-1-dead-link-handoff" — do not edit.
// Input-event subset of the capture (RFC_DETERMINISTIC_SIMULATION.md §2); replay via SimTimeline.
@file:Suppress("ktlint")

package com.ditchoom.socket.quic.sim.fixtures

import com.ditchoom.socket.InternetAccess
import com.ditchoom.socket.NetworkState
import com.ditchoom.socket.quic.sim.SimError
import com.ditchoom.socket.quic.sim.SimFixture
import com.ditchoom.socket.quic.sim.simFixture
import com.ditchoom.socket.transport.NetworkId
import com.ditchoom.socket.transport.NetworkKind
import kotlin.time.Duration.Companion.nanoseconds

internal val walk20260910Conn1DeadLinkHandoff: SimFixture =
    simFixture("walk-2026-09-10-conn-1-dead-link-handoff") {
        at(0.nanoseconds) datagramIn "5dc5d712cabd113d66bc8c56384596325bc96b3beba270a953dc81c4c30240245c80f1f2399fd77b1062391710ca5f5f4129feeebf4cf9891e31ccf9d7a44a79e3b5"
        at(3543973583.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(3564014083.nanoseconds) net NetworkState.Routable(NetworkId.Link(NetworkKind.Cellular, 12L), InternetAccess.Unobserved)
        at(4199144000.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(4859249250.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(5513395958.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(6166492208.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(6628426250.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(6822212041.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(7481223250.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(8142809916.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(8797267166.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(9451996000.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(9881761000.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(10113082000.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(10774215166.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(11428160000.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(12090298125.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(12752903625.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(13387897833.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(13411257833.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(14074000291.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(14736844125.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(15393343708.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(16055066625.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(16710531458.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(17368615916.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(18030102625.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(18686305708.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(19341830666.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(20003476916.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(20659041250.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(21318784833.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(21974345375.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(22633055958.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(23288693000.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(23946201625.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(24603979250.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(25259734041.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(25916086041.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(26573255750.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(27231013750.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(27887402000.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(28547872583.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(29214533666.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(29877351958.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(30239237833.nanoseconds) recvError SimError("com.ditchoom.socket.quic.QuicError.IdleTimeout: IdleTimeout (0x-1)")
        runFor(30239237833.nanoseconds)
    }
