// GENERATED by TraceToFixture from recorded trace "walk-2026-09-20-leg-3-conn-1-downlink-blackout" — do not edit.
// Input-event subset of the capture (RFC_DETERMINISTIC_SIMULATION.md §2); replay via SimTimeline.
@file:Suppress("ktlint")

package com.ditchoom.socket.quic.sim.fixtures

import com.ditchoom.socket.InternetAccess
import com.ditchoom.socket.NetworkState
import com.ditchoom.socket.quic.sim.SimError
import com.ditchoom.socket.quic.sim.SimFixture
import com.ditchoom.socket.quic.sim.simFixture
import com.ditchoom.socket.transport.NetworkId
import com.ditchoom.socket.transport.NetworkKind
import kotlin.time.Duration.Companion.nanoseconds

internal val walk20260920Leg3Conn1DownlinkBlackout: SimFixture =
    simFixture("walk-2026-09-20-leg-3-conn-1-downlink-blackout") {
        at(0.nanoseconds) datagramIn "425f844433c367ed8a17c71266556f6369ec5b3421f52c2a9dcb0c602535fd304b86b5ad768d4b91e5dcbb09dc55b6d266c4db16a649d3bc1f824152c457adc8a2d4091ae534"
        at(1083044541.nanoseconds) net NetworkState.Routable(NetworkId.Link(NetworkKind.Cellular, 2L), InternetAccess.Unobserved)
        at(3095389416.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(4861340291.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(7405295208.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(8829881541.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(13054947083.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(14545045666.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(17771219125.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(19550758333.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(21688012416.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(23487649958.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(26695365875.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(28827276125.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: send failed (errno=57)")
        at(30269813041.nanoseconds) recvError SimError("com.ditchoom.socket.quic.QuicError.IdleTimeout: IdleTimeout (0x-1)")
        runFor(30269813041.nanoseconds)
    }
