// GENERATED by TraceToFixture from recorded trace "walk-2026-09-24-v4-conn-1-cellular-not-yet-passing" — do not edit.
// Input-event subset of the capture (RFC_DETERMINISTIC_SIMULATION.md §2); replay via SimTimeline.
@file:Suppress("ktlint")

package com.ditchoom.socket.quic.sim.fixtures

import com.ditchoom.socket.InternetAccess
import com.ditchoom.socket.NetworkState
import com.ditchoom.socket.quic.sim.SimError
import com.ditchoom.socket.quic.sim.SimFixture
import com.ditchoom.socket.quic.sim.simFixture
import com.ditchoom.socket.transport.NetworkId
import com.ditchoom.socket.transport.NetworkKind
import kotlin.time.Duration.Companion.nanoseconds

internal val walk20260924V4Conn1CellularNotYetPassing: SimFixture =
    simFixture("walk-2026-09-24-v4-conn-1-cellular-not-yet-passing") {
        at(0.nanoseconds) datagramIn "52bb216f8b34fa5b37325c97307ba84525a4965ace1269ac69411d464738429e871608b8e9dc1ccb127f31197730c49d6b69c487cae8091d8a"
        at(10117590256.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(10369566298.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(10625579944.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(10878218902.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(11130925881.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(11383399006.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(11636881818.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(12028853068.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(12033514162.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(12808450932.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(12817682026.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(14364749473.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(14431298328.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(15148477181.nanoseconds) net NetworkState.Offline
        at(15421655411.nanoseconds) net NetworkState.Routable(NetworkId.Link(NetworkKind.Cellular, 12218292686861L), InternetAccess.Observed.Pending)
        at(17522539368.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(17620051972.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(23798776032.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(23938911449.nanoseconds) recvError SimError("com.ditchoom.socket.udp.DatagramSendException: destination unreachable")
        at(30220293582.nanoseconds) recvError SimError("com.ditchoom.socket.quic.QuicError.IdleTimeout: IdleTimeout (0x-1)")
        runFor(30220293582.nanoseconds)
    }
